name: URL Shortener CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Workflow is working"

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 22

      # - name: Install Dependencies
      #   working-directory: ./backend
      #   run: npm install

      # - name: Start Application
      #   working_directory: ./backend
      #   run: node src/server.js & sleep 10

      # - name: Health Check
      #   run: curl --fail http://localhost:12000/health

      # - name: Build Docker Image
      #   working_directory: ./backend
      #   run: docker build -t my-backend .
