name: URL Shortener CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Application
        working-directory: ./backend
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}

        run: node src/server.js & sleep 10

      - name: Health Check
        run: curl --fail http://localhost:12000/health

      - name: Build Docker Image
        working-directory: ./backend
        run: docker build -t my-backend .
